#ifndef __S2_AURORA_VTUNE_PRO_HD_TCP_IP_0_H__
#define __S2_AURORA_VTUNE_PRO_HD_TCP_IP_0_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_POWER_ON_DIG_INPUT 0
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_POWER_OFF_DIG_INPUT 1
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_KEY_0_DIG_INPUT 2
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_KEY_1_DIG_INPUT 3
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_KEY_2_DIG_INPUT 4
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_KEY_3_DIG_INPUT 5
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_KEY_4_DIG_INPUT 6
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_KEY_5_DIG_INPUT 7
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_KEY_6_DIG_INPUT 8
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_KEY_7_DIG_INPUT 9
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_KEY_8_DIG_INPUT 10
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_KEY_9_DIG_INPUT 11
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_KEY_DOT_DIG_INPUT 12
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_ENTER_DIG_INPUT 13
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_CLEAR_DIG_INPUT 14
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_CH_UP_DIG_INPUT 15
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_CH_DOWN_DIG_INPUT 16
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_CC_DIG_INPUT 17
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_CC_ON_DIG_INPUT 18
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_CC_OFF_DIG_INPUT 19
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_CC_TYPE2_DIG_INPUT 20

#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_PRE_DIG_INPUT 21
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_PRE_ARRAY_LENGTH 10

/*
* ANALOG_INPUT
*/




/*
* DIGITAL_OUTPUT
*/
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_PRESET_SAVED_DIG_OUTPUT 0
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_CC_FB_DIG_OUTPUT 1


/*
* ANALOG_OUTPUT
*/
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_CONNECTION_ANALOG_OUTPUT 0

#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_TV_CHANNEL$_STRING_OUTPUT 1
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_DEBUG$_STRING_OUTPUT 2


/*
* Direct Socket Variables
*/

#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_SERVER_SOCKET 0
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_SERVER_STRING_MAX_LEN 1000
START_SOCKET_DEFINITION( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __SERVER )
{
   int SocketStatus;
   enum ESplusSocketType eSocketType;
   int SocketID;
   void *SocketPtr;
CREATE_SOCKET_STRING( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, SocketRxBuf, __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_SERVER_STRING_MAX_LEN );
};



/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_IP_ADDRESS_STRING_PARAMETER 10
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_IP_ADDRESS_PARAM_MAX_LEN 21
CREATE_STRING_STRUCT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __IP_ADDRESS, __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_IP_ADDRESS_PARAM_MAX_LEN );


/*
* INTEGER
*/
CREATE_INTARRAY1D( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __PRESET, 10 );;


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_RX$_STRING_MAX_LEN 255
CREATE_STRING_STRUCT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __RX$, __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_RX$_STRING_MAX_LEN );
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_CMD$_STRING_MAX_LEN 15
CREATE_STRING_STRUCT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __CMD$, __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_CMD$_STRING_MAX_LEN );
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_TEMPSTRING$_STRING_MAX_LEN 255
CREATE_STRING_STRUCT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __TEMPSTRING$, __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_TEMPSTRING$_STRING_MAX_LEN );
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_IP_ADDR_STRING_MAX_LEN 15
CREATE_STRING_STRUCT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __IP_ADDR, __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_IP_ADDR_STRING_MAX_LEN );
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_SKEYPAD_STRING_MAX_LEN 6
CREATE_STRING_STRUCT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __SKEYPAD, __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_SKEYPAD_STRING_MAX_LEN );
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_SCURRENT_CHANNEL_STRING_MAX_LEN 6
CREATE_STRING_STRUCT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __SCURRENT_CHANNEL, __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_SCURRENT_CHANNEL_STRING_MAX_LEN );
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_SPRE_ARRAY_NUM_ELEMS 10
#define __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_SPRE_ARRAY_NUM_CHARS 6
CREATE_STRING_ARRAY( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __SPRE, __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_SPRE_ARRAY_NUM_ELEMS, __S2_Aurora_VTUNE_PRO_HD_TCP_IP_0_SPRE_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __PRE );
   unsigned short __CC_MODE;
   unsigned short __VALID_IP;
   unsigned short __TV_CHANNEL;
   unsigned short __CURRENT_CHANNEL;
   unsigned short __IP_PORT;
   unsigned short __X;
   unsigned short __CHAN_SIZE;
   DECLARE_STRING_STRUCT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __RX$ );
   DECLARE_STRING_STRUCT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __CMD$ );
   DECLARE_STRING_STRUCT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __TEMPSTRING$ );
   DECLARE_STRING_STRUCT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __IP_ADDR );
   DECLARE_STRING_STRUCT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __SKEYPAD );
   DECLARE_STRING_STRUCT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __SCURRENT_CHANNEL );
   DECLARE_STRING_ARRAY( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __SPRE );
   DECLARE_SOCKET( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __SERVER );
   DECLARE_STRING_STRUCT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __IP_ADDRESS );
};

START_NVRAM_VAR_STRUCT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0 )
{
   DECLARE_INTARRAY( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __PRESET );
};

DEFINE_WAITEVENT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __SPLS_TMPVAR__WAITLABEL_0__ );
DEFINE_WAITEVENT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, REQ_CHANNEL );
DEFINE_WAITEVENT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, SAVE_PRESET );
DEFINE_WAITEVENT( S2_Aurora_VTUNE_PRO_HD_TCP_IP_0, __SPLS_TMPVAR__WAITLABEL_1__ );


#endif //__S2_AURORA_VTUNE_PRO_HD_TCP_IP_0_H__

